import type { Application, Job, User } from '@/types';

export const mockUsers: Array<User & { password: string }> = [
  {
    id: 'user-1',
    name: 'Ana Pereira',
    email: 'ana@hiretrack.dev',
    password: '123456',
    role: 'developer',
    location: 'São Paulo, SP',
    mainStack: 'Vue, TypeScript, Node.js',
  },
];

export const mockJobs: Job[] = [
  {
    id: 'job-frontend-platform',
    title: 'Frontend Engineer - Platform',
    company: 'CloudNova',
    location: 'Remoto Brasil',
    salaryRange: 'R$ 13.000 - R$ 17.000',
    workModel: 'remoto',
    seniority: 'senior',
    stack: ['Vue', 'TypeScript', 'GraphQL'],
    description: 'Construa interfaces de produto para uma plataforma SaaS usada por times de engenharia distribuídos.',
    responsibilities: [
      'Evoluir o design system em Vue 3',
      'Integrar fluxos com APIs GraphQL',
      'Acompanhar métricas de performance no frontend',
    ],
    requirements: ['Vue 3', 'TypeScript avançado', 'Experiência com testes automatizados'],
    postedAt: '2026-04-24',
    recruiterName: 'Marina Costa',
    contactEmail: 'marina@cloudnova.dev',
  },
  {
    id: 'job-fullstack-fintech',
    title: 'Full Stack Developer',
    company: 'LedgerPay',
    location: 'São Paulo, SP',
    salaryRange: 'R$ 10.000 - R$ 14.000',
    workModel: 'hibrido',
    seniority: 'pleno',
    stack: ['React', 'Node.js', 'PostgreSQL'],
    description: 'Atue em produtos financeiros com foco em conciliação, observabilidade e experiência do usuário.',
    responsibilities: ['Desenvolver features ponta a ponta', 'Criar testes de integração', 'Apoiar discovery técnico'],
    requirements: ['Node.js', 'REST ou GraphQL', 'Banco relacional'],
    postedAt: '2026-04-20',
    recruiterName: 'Rafael Lima',
    contactEmail: 'talentos@ledgerpay.com',
  },
  {
    id: 'job-mobile-health',
    title: 'Mobile Developer',
    company: 'VivaHealth',
    location: 'Belo Horizonte, MG',
    salaryRange: 'R$ 8.000 - R$ 11.000',
    workModel: 'presencial',
    seniority: 'pleno',
    stack: ['React Native', 'TypeScript', 'GraphQL'],
    description: 'Desenvolva experiências móveis para acompanhamento de saúde preventiva.',
    responsibilities: ['Construir telas mobile', 'Consumir GraphQL', 'Colaborar com produto e design'],
    requirements: ['React Native', 'TypeScript', 'Boas práticas de acessibilidade'],
    postedAt: '2026-04-18',
    recruiterName: 'Beatriz Rocha',
    contactEmail: 'people@vivahealth.com',
  },
  {
    id: 'job-junior-vue',
    title: 'Junior Vue Developer',
    company: 'Studio Orbit',
    location: 'Curitiba, PR',
    salaryRange: 'R$ 4.500 - R$ 6.500',
    workModel: 'remoto',
    seniority: 'junior',
    stack: ['Vue', 'Tailwind CSS', 'Vitest'],
    description: 'Participe da criação de aplicações web para clientes B2B com mentoria técnica diária.',
    responsibilities: ['Implementar componentes', 'Corrigir bugs', 'Escrever testes unitários'],
    requirements: ['HTML/CSS sólido', 'Noções de Vue', 'Git'],
    postedAt: '2026-04-16',
    recruiterName: 'João Moreira',
    contactEmail: 'jobs@studioorbit.dev',
  },
  {
    id: 'job-backend-go',
    title: 'Backend Engineer Go',
    company: 'DataForge',
    location: 'Recife, PE',
    salaryRange: 'R$ 15.000 - R$ 19.000',
    workModel: 'hibrido',
    seniority: 'senior',
    stack: ['Go', 'Kubernetes', 'GraphQL'],
    description: 'Projete serviços de alta disponibilidade para pipelines de dados em larga escala.',
    responsibilities: ['Criar APIs resilientes', 'Operar workloads em Kubernetes', 'Revisar arquitetura'],
    requirements: ['Go', 'Mensageria', 'Observabilidade'],
    postedAt: '2026-04-12',
    recruiterName: 'Camila Duarte',
    contactEmail: 'camila@dataforge.io',
  },
];

export const mockApplications: Application[] = [
  {
    jobId: 'job-frontend-platform',
    status: 'salvo',
    updatedAt: '2026-04-25T10:00:00.000Z',
    notes: 'Comparar com vaga atual antes de aplicar.',
    history: [{ status: 'salvo', changedAt: '2026-04-25T10:00:00.000Z' }],
  },
  {
    jobId: 'job-fullstack-fintech',
    status: 'aplicado',
    updatedAt: '2026-04-23T11:30:00.000Z',
    notes: 'Aplicação enviada pelo LinkedIn.',
    history: [
      { status: 'salvo', changedAt: '2026-04-22T08:00:00.000Z' },
      { status: 'aplicado', changedAt: '2026-04-23T11:30:00.000Z' },
    ],
  },
  {
    jobId: 'job-mobile-health',
    status: 'entrevista',
    updatedAt: '2026-04-22T14:15:00.000Z',
    notes: 'Preparar exemplos de acessibilidade mobile.',
    nextInterviewAt: '2026-05-08T14:00',
    history: [
      { status: 'salvo', changedAt: '2026-04-20T10:00:00.000Z' },
      { status: 'aplicado', changedAt: '2026-04-21T09:00:00.000Z' },
      { status: 'entrevista', changedAt: '2026-04-22T14:15:00.000Z' },
    ],
  },
  {
    jobId: 'job-backend-go',
    status: 'recusado',
    updatedAt: '2026-04-19T09:20:00.000Z',
    notes: 'A vaga exigia mais experiência com Kubernetes.',
    history: [
      { status: 'salvo', changedAt: '2026-04-18T09:00:00.000Z' },
      { status: 'recusado', changedAt: '2026-04-19T09:20:00.000Z' },
    ],
  },
];
